export const parks = [
    "Disneyland Park - California, USA",
    "Disney California Adventure Park - California, USA",
    "Magic Kingdom - Florida, USA",
    "EPCOT - Florida, USA",
    "Disney's Hollywood Studios - Florida, USA",
    "Disney's Animal Kingdom - Florida, USA",
    "Tokyo Disneyland - Chiba, Japan",
    "Tokyo DisneySea - Chiba, Japan",
    "Disneyland Paris - Île-de-France, France",
    "Walt Disney Studios Park - Île-de-France, France",
    "Hong Kong Disneyland - Hong Kong, China",
    "Shanghai Disneyland - Shanghai, China",
    "Walt Disney World - Florida, USA",
] as const;
